// Content for the SIP viva guide. Numbers are taken from the JHS MES v3.0 workbook
// (demonstration dataset) and from the SIP deck.
module.exports.concepts = [
  {
    t: "Batch Number",
    line: "The identifier printed on the pack (e.g. JHS-26433). It is what the customer, the trade and the regulator see.",
    formula: null,
    vars: [],
    ex: "In the workbook, JHS-26433 appears on 6 production runs between 12-Jun-26 and 04-Sep-26: three products (Dabur Red Soft, Dabur Red Medium, Babool Family Pack) and four colours. In the full demonstration dataset, 364 batch numbers cover 1,529 runs and each recurs three to six times.",
    why: "Batch numbers are drawn from a finite annual series, so they repeat. A lookup keyed on them can silently return the wrong run, and then the investigation looks at the wrong machine and the wrong material lot.",
    say: "The batch number is a printed identifier, not a database key. It repeats by design, so I kept it exactly as it is and added a unique internal key alongside it.",
  },
  {
    t: "Production Run ID",
    line: "The internal, unique key for one manufacturing occurrence, in the format PR-year-sequence (e.g. PR-2026-00630).",
    formula: "Printed fields (Batch + Product + Colour + Mfg. Date)  →  Trace Report  →  Production Run ID",
    vars: [["Assigned", "When the run is logged in RAW Production (column A)."], ["Carried by", "QC, dispatch, downtime and material-issue records, and the complaint register."], ["Checked by", "Master Traceability column 'Data Validation Status', which flags 'Duplicate Run ID'."]],
    ex: "Batch JHS-26433 + Dabur Red Toothbrush — Medium + RED + 14-Jul-26 → exactly one record → PR-2026-00630. Every other record for that run (inspection AR-2026-0630, dispatch DN-26-00511, downtime DT-00705 and DT-00706) is joined on it.",
    why: "A key must be unique. Separating the printed identifier from the relational key is the single most important design decision in the project.",
    say: "Batch number is what's printed; Production Run ID is what connects. The system translates one into the other once, and from then on everything is joined on the Run ID.",
  },
  {
    t: "Forward traceability (downstream)",
    line: "Starting from an input (a material or component lot) and following it forward to every run, batch, shipment and customer it reached.",
    formula: "Component lot  →  every production run that used it  →  batches  →  dispatch numbers / customers",
    vars: [],
    ex: "Handle lot HL-DBR-26-0519 → 3 runs (PR-2026-00630, -00631, -00710) → 8,698 good units exposed → dispatches DN-26-00511, -00517, -00578.",
    why: "It answers the containment and recall question: if a lot is bad, what else is affected, and where did it go? It turns recall scope into a calculation instead of an estimate.",
    say: "Forward traceability starts from a suspect lot and tells me everything it touched. In my workbook that's Direction 2 of the Reverse Trace sheet.",
    note: "Naming: the workbook's sheet is called 'Reverse Trace' because it reverses the complaint's direction (complaint → run → lot becomes lot → all runs). In textbook terms, lot → runs is forward/downstream traceability. If the panel uses the textbook terms, match them and explain the sheet name.",
  },
  {
    t: "Reverse (backward / upstream) traceability",
    line: "Starting from a finished product (or a complaint) and going back to what went into it and how it was made.",
    formula: "Complaint / finished pack  →  production run  →  materials, machine, shift, QC result",
    vars: [],
    ex: "Complaint CMP-26-0024 ('Bristle fall-out during use') → JHS-26433 + product + colour + date → PR-2026-00630 → tufting machine DBR-TUF-11, shift A, handle lot HL-DBR-26-0519, bristle supplier DuPont Filaments, nylon AR-2026-0100, QC PASSED.",
    why: "It is how an investigation starts. Without it, QA has to search each departmental register by hand.",
    say: "Backward traceability takes me from the customer's pack to the run and its inputs. In the workbook that's the Trace Report, and Direction 1 of the Reverse Trace sheet.",
  },
  {
    t: "Material genealogy",
    line: "The parent–child record of which input lots went into which output. It's a family tree for the product.",
    formula: null,
    vars: [["For a toothbrush", "Handle lot, SFG code, PP grade and lot, PP AR number, masterbatch lot, mould number, moulding machine, bristle supplier, nylon AR numbers, brass wire lot, hygienic cap lot."]],
    ex: "PR-2026-00630 ← handle lot HL-DBR-26-0519 ← PP 1120HP lot PPL-26-0040, masterbatch MBL-26-0160, mould MLD-726; bristles from DuPont Filaments, nylon white AR-2026-0100, brass wire BRW-26-0040.",
    why: "Genealogy is what makes both directions of traceability possible. In moulding, one handle lot feeds one to three assembly runs, so the tree branches.",
    say: "Genealogy records what went into what. It's the data that lets reverse trace work.",
  },
  {
    t: "Master data",
    line: "Slow-changing reference data, defined once: machines (with ideal speed and OEE targets), SKUs, lines, shifts, defect catalogue, materials, customers.",
    formula: null,
    vars: [["Where", "The LOOKUP TABLES sheet (layer 1)."]],
    ex: "Machine master row: DBR-TUF-11, Bristle Tufting Machine 1, ideal speed 620 units/hr, ideal cycle time 5.81 s, target OEE 80%.",
    why: "If master data is typed freely in each register, 'DBR-TUF-11' and 'DBR TUF 11' become two machines and every SUMIFS and lookup breaks.",
    say: "Master data defines the allowed values once. Everything else points at it.",
  },
  {
    t: "Transaction data",
    line: "Event records created every day: production runs, QC inspections, dispatches, downtime events, material issues (MRS) and goods receipts (GRN).",
    formula: null,
    vars: [["Where", "Layer 2: RAW Production, RAW Handle, RAW QC, RAW Dispatch, Downtime, Material Req. Slip, GRN Incoming. These are the only sheets users type into."]],
    ex: "Downtime DT-00705: PR-2026-00630, DBR-TUF-11, shift A, Material Shortage, 'Blister film not issued', 109 minutes, Unplanned.",
    why: "Keeping events separate from reference data and from calculations is basic data modelling. It keeps the system consistent and maintainable.",
    say: "Master data is 'what exists'; transaction data is 'what happened'.",
  },
  {
    t: "Data validation",
    line: "Rules that stop bad input at the point of entry, plus checks that flag problems after entry.",
    formula: "Entry rule: dropdown list = named range from master data (e.g. List_Products, List_Shifts, List_Machines)\nPost-entry check: IF(... ,\"Run Not In QC\" / \"Invalid Handle Lot\" / \"Quantity Mismatch\" / \"Duplicate Run ID\", \"OK\")",
    vars: [["Entry validation", "Every coded field is a dropdown; the error message says 'Pick from the list, or add the new value in LOOKUP TABLES first.'"], ["Record checks", "RAW Production 'Transaction Validation Status'; Master Traceability 'Data Validation Status'."], ["Quantity rule", "Actual = Good + Rejected + Reworked."]],
    ex: "PR-2026-00630: 1,878 good + 20 rejected + 13 reworked = 1,911 actual → status OK.",
    why: "Every downstream calculation depends on values matching exactly. Validation before calculation is what makes the numbers trustworthy.",
    say: "I prevent bad input where I can, and flag it where I can't. The honest gap is that the Run ID in the QC register is checked after entry rather than forced by a dropdown; a database would enforce it as a foreign key.",
  },
  {
    t: "SUMIFS",
    line: "Adds up a column only for the rows that meet several conditions.",
    formula: "=SUMIFS(sum_range, criteria_range1, criteria1, criteria_range2, criteria2, …)",
    vars: [["sum_range", "What to add, e.g. F_Total (total output per run)."], ["criteria_range / criteria", "Filters, e.g. F_Brand = Crit_Brand, F_Shift = Crit_Shift, F_Date >= Crit_From, F_Date <= Crit_To."]],
    ex: "Dashboard actual production: =SUMIFS(F_Total, F_Brand,Crit_Brand, F_Shift,Crit_Shift, F_Date,Crit_From, F_Date,Crit_To) → 5,842,931 units. Downtime per run: =SUMIFS(DT_Minutes, DT_Run, PR-2026-00630) → 109 + 154 = 263 minutes.",
    why: "It is how one filter block drives every KPI, and how events recorded separately (downtime) are rolled up to the run they belong to.",
    say: "SUMIFS is a conditional total. The dashboard is basically SUMIFS under a shared filter.",
  },
  {
    t: "COUNTIFS",
    line: "Counts the rows that meet several conditions.",
    formula: "=COUNTIFS(criteria_range1, criteria1, criteria_range2, criteria2, …)",
    vars: [],
    ex: "Records in scope: =COUNTIFS(F_Brand,Crit_Brand, F_Shift,Crit_Shift, F_Date,Crit_From, F_Date,Crit_To) → 1,529. Open complaints: =COUNTIFS(CP_Brand,Crit_Brand, CP_Status,\"Open\"). Reverse trace: =COUNTIF(MT_HandleLot, \"HL-DBR-26-0519\") → 3 runs.",
    why: "Counts tell the user the basis of every figure (records in scope) and drive status tiles and exposure checks.",
    say: "COUNTIFS counts; SUMIFS totals. Same filter logic.",
  },
  {
    t: "INDEX / MATCH",
    line: "MATCH finds the position of a key in a column; INDEX returns the value at that position from another column.",
    formula: "=INDEX(return_range, MATCH(lookup_value, lookup_range, 0))\nMultiple matches: =INDEX(return_range, SMALL(IF(condition, ROW(range)-MIN(ROW(range))+1), k))",
    vars: [["0 in MATCH", "Exact match only."], ["SMALL(IF(...), k)", "Position of the k-th row that meets the condition, so the report can list every match, not just the first."]],
    ex: "Reverse Trace: =IFERROR(INDEX(MT_HandleLot, MATCH(\"PR-2026-00630\", MT_Run, 0)), \"—\") → HL-DBR-26-0519. Trace Report row k: =INDEX(MT_Batch, SMALL(IF(MT_Match=1, ROW(MT_Match)-MIN(ROW(MT_Match))+1), k)).",
    why: "Unlike VLOOKUP, it can look left, doesn't break when a column is inserted, and works with named ranges. MATCH returns only the first match, which is exactly why the key has to be unique.",
    say: "INDEX-MATCH is my lookup. And because MATCH stops at the first match, a repeating key like batch number would silently return the wrong run. That's the technical reason for the Run ID.",
  },
  {
    t: "OEE (Overall Equipment Effectiveness)",
    line: "The share of planned production time that was truly productive: running, at full speed, making good product.",
    formula: "OEE = Availability × Performance × Quality",
    vars: [["Availability", "Loss from stops."], ["Performance", "Loss from slow running."], ["Quality", "Loss from rejects."]],
    ex: "PR-2026-00630: 45.2% × 85.2% × 98.3% = 37.9%. Whole dataset: 84.6% × 89.6% × 97.6% = 74.0% (world-class reference 85%).",
    why: "A single loss number (like the line study's 40.7%) says there is a problem; OEE says which kind of problem, and so who should act: maintenance, process or quality.",
    say: "OEE splits the gap into stops, speed and rejects. On PR-2026-00630, the problem was clearly availability: two material shortages, not the machine.",
  },
  {
    t: "Availability",
    line: "Of the time the line was supposed to run, how much did it actually run?",
    formula: "Availability = Actual Run Time ÷ Planned Production Time\nRun Time = Planned Production Time − Downtime",
    vars: [["Planned production time", "Scheduled minutes for the run (480 for one 8-hour shift)."], ["Downtime", "Sum of stoppage minutes logged against the Run ID."]],
    ex: "PR-2026-00630: 480 − 263 = 217 min run time; 217 ÷ 480 = 45.2%. Dataset: 620,878 ÷ 733,920 = 84.6%.",
    why: "It isolates stoppage losses: breakdowns, material shortages, changeovers.",
    say: "Did it run when it was scheduled to?",
  },
  {
    t: "Performance",
    line: "When the line was running, did it run at its ideal speed?",
    formula: "Performance = Total Count ÷ Ideal Output Capability\nIdeal Output Capability = Run Time (min) × Ideal Speed (units/hr) ÷ 60\n(equivalently: Ideal Cycle Time × Total Count ÷ Run Time)",
    vars: [["Total count", "All units produced, good or bad."], ["Ideal speed", "From the machine master, not the production record."]],
    ex: "PR-2026-00630: 217 × 620 ÷ 60 = 2,242 ideal units; 1,911 ÷ 2,242 = 85.2%.",
    why: "It isolates speed losses: minor stops, slow running. Taking ideal speed from the machine master means performance measures the equipment, not the data entry.",
    say: "When it ran, did it run at the speed it should have?",
  },
  {
    t: "Quality (OEE factor)",
    line: "Of everything produced, how much was good first time?",
    formula: "Quality = Good Count ÷ Total Count",
    vars: [],
    ex: "PR-2026-00630: 1,878 ÷ 1,911 = 98.3%. Dataset: 5,703,481 ÷ 5,842,931 = 97.6%.",
    why: "It isolates reject and rework losses.",
    say: "Was what it made saleable?",
  },
  {
    t: "Yield",
    line: "Share of output that is good.",
    formula: "Yield = Good Quantity ÷ Actual (Total) Quantity",
    vars: [],
    ex: "PR-2026-00630: 1,878 ÷ 1,911 = 98.3%. Dashboard: 97.6%.",
    why: "It's the quality KPI management watches. In this workbook it is numerically the same as the OEE quality factor. The difference is the purpose: yield is a stand-alone KPI; quality rate is one factor in OEE.",
    say: "I defined yield as first-pass good output over total output. Some plants define yield against input material; I'd align to the plant's definition in a live rollout.",
  },
  {
    t: "Rejection rate",
    line: "Share of output rejected.",
    formula: "Rejection % = Rejected Quantity ÷ Actual (Total) Quantity",
    vars: [],
    ex: "PR-2026-00630: 20 ÷ 1,911 = 1.0%. Dashboard: 2.0%. Note that good + rejected + reworked = actual, so yield + rejection % + rework % = 100%.",
    why: "It is paired with the defect Pareto, which ranks defect categories by batches affected so attention goes where most of the loss is.",
    say: "Rejection rate says how much; the Pareto says what kind.",
  },
  {
    t: "Production efficiency",
    line: "Did we produce what we planned?",
    formula: "Production Efficiency = Actual Quantity ÷ Planned Quantity",
    vars: [],
    ex: "PR-2026-00630: 1,911 ÷ 5,240 = 36.5%, status 'Below Plan'. Dashboard: 5,842,931 ÷ 6,630,870 = 88.1%.",
    why: "It is a planning and schedule-adherence measure. It is not the same as OEE performance, which compares with ideal speed during run time only.",
    say: "Efficiency is against the plan; performance is against the machine's ideal speed.",
  },
  {
    t: "Downtime",
    line: "Time the line was scheduled to run but didn't, recorded as individual events with category, reason and minutes.",
    formula: "Downtime (per run) = SUMIFS(DT_Minutes, DT_Run, Run ID)\nPlanned downtime = SUMIFS(DT_Minutes, DT_Run, Run ID, DT_Loss, \"Planned\")",
    vars: [["Category", "e.g. Machine Breakdown, Material Shortage, Changeover."], ["Loss type", "Planned (maintenance, cleaning) or Unplanned (breakdowns, shortages, changeovers)."]],
    ex: "PR-2026-00630: DT-00705 'Blister film not issued' 109 min + DT-00706 'Back card shortage' 154 min = 263 min, both Unplanned. Dataset: 85,738 unplanned + 27,304 planned = 113,042 minutes.",
    why: "A single total can't be acted on. Events with a category and reason feed the downtime Pareto and tell you who needs to act.",
    say: "I record every stoppage as an event against the run, not a single total. That's what makes availability explainable.",
  },
  {
    t: "Ideal speed (and ideal cycle time)",
    line: "The rated maximum output rate of a machine under ideal conditions.",
    formula: "Ideal Cycle Time (s) = 3,600 ÷ Ideal Speed (units/hr)\nIdeal output = Time × Ideal Speed",
    vars: [["Line study", "100 units/minute (main toothpaste line)."], ["Workbook", "DBR-TUF-11: 620 units/hr → 5.81 s per unit."]],
    ex: "Line study: 675 effective min × 100 units/min = 67,500 ideal units. PR-2026-00630: 217 run min × 620/60 = 2,242 ideal units.",
    why: "It is the benchmark for performance. Holding it in the machine master means one change there updates the whole OEE engine.",
    say: "Ideal speed is a property of the machine, so it lives in the machine master, not on the production record.",
  },
];

module.exports.jhs = {
  facts: [
    ["Company", "JHS Svendgaard Laboratories Ltd. Established 1997 as a toothbrush manufacturer; now makes the full oral-care range."],
    ["Business model", "Contract manufacturing for domestic and international brands (publicly named clients include Amway India and Dabur India), plus its own brands."],
    ["Products", "Toothpaste (high-volume: dispensing, blending, homogenisation, tube filling); toothbrushes (handle moulding, tufting, trimming, cap assembly, packing); mouthwash (lower-volume, order-based single line)."],
    ["Where I was", "Operations Department, manufacturing location at Kala-Amb, Himachal Pradesh. Corporate office in New Delhi."],
    ["When", "1 June – 17 July 2026 (seven weeks)."],
    ["Guides", "External: Mr. Paramveer Singh, Chief Executive Officer, JHS Svendgaard. Internal: Dr. Vineet Tiwari, Associate Professor, IIIT Allahabad."],
  ],
  learnt: [
    ["Planning & procurement", "Planning and buying are deliberately separated: the plan says what is needed, procurement decides how to get it. Material requirement planning connects the two."],
    ["Inbound & warehouse", "A material gets a traceable identity at the gate before storage: gate verification, weighbridge, quarantine, sampling, traceability label."],
    ["QC laboratory", "Testing a material and releasing a batch are different decisions, recorded separately."],
    ["Quality assurance", "Line clearance is graded (A and B). A retained sample of every batch is kept through expiry so a later complaint can be investigated against evidence."],
    ["Paste plant", "Material keeps its identity from weighbridge through release; high-volume lines where loss is measured against rated speed."],
    ["Moulding", "A brush first gets its identity at the handle lot; one moulding lot is consumed by one to three assembly runs."],
    ["Tufting", "Filament is anchored into the handle and trimmed; bristle retention is decided here."],
    ["Maintenance & losses", "The plant quantifies its own losses through OEE and Total Productive Maintenance."],
    ["Common thread", "Every record exists because some later activity will need it."],
  ],
};

module.exports.questions = [
  ["Tell us about JHS.", "JHS Svendgaard is an oral-care manufacturer, established in 1997 as a toothbrush maker. A large part of its business is contract manufacturing of toothpaste, toothbrushes and mouthwash for domestic and international brands, alongside its own. I was in the Operations Department at the Kala-Amb plant in Himachal Pradesh."],
  ["What did you learn during the plant induction?", "Three things stand out. A material gets a traceable identity at the gate before it's stored. QC testing and QA release are separate decisions. And every record exists because a later activity needs it. Each of those later shaped part of the MES."],
  ["What is the difference between QC and QA?", "QC tests a material or product against specification and records the result. QA reviews the batch record, line clearance and QC results, then releases or holds the batch. The MES keeps QC status and release status as separate fields for that reason."],
  ["What is line clearance?", "Before a new batch starts, the line is checked and cleared of the previous product's materials, labels and documents so nothing is mixed up. JHS grades it into A and B levels. Explain the criteria as the plant's SOP defines them."],
  ["Why does contract manufacturing make traceability more important?", "The brand owner answers to the consumer. When a complaint comes in, the client expects the manufacturer to identify the run, materials and QC record quickly and to scope any recall precisely."],
  ["Why Excel?", "It is what the plant already uses, it needs no new licences, infrastructure or IT approval, and people can use it without training. That let me build and test a working prototype within seven weeks. The value is in the data model: masters, registers, one key, one-directional flow. That carries over unchanged to any platform."],
  ["Why not SQL?", "SQL is the right destination for scale and multi-user use, and it's in my future scope. For an internship prototype, it would have needed a server, IT approval and user interfaces before anyone could test anything. I designed the workbook like a database, with one table per entity and a unique key, so migration is mostly a move, not a redesign. The sensible sequence is data discipline first, barcode capture second, then database migration."],
  ["Why not Power BI?", "Power BI is a presentation tool; it still needs a clean, connected data model underneath. The problem I found was the data structure, not the visualisation. Once the data is structured, Power BI can sit on top of it. That's future scope."],
  ["Why an MES, and not just better reports?", "Because the problem was in how the data was connected, not how it was displayed. An MES sits between planning (ERP) and the shop floor: it records what actually happened in each run and connects production, quality, material and dispatch. Better reports on disconnected registers would still need manual consolidation."],
  ["What was your personal contribution?", "The plant process study and the twelve-hour line observation; the requirement definition; the data model, including separating the printed batch number from a unique Production Run ID and the four-field identification logic; building all 27 sheets (registers, calculation engine, dashboards, Trace Report, Reverse Trace, Complaint Tool); and the testing: 106 calculation checks against independently computed values plus 80 filter-context checks."],
  ["What was the most difficult part?", "Not the Excel. It was understanding the operation well enough to know what questions the system had to answer, and the batch-number issue. I only found out during testing that batch numbers repeat, and I had to rework the identification logic."],
  ["What would you change if you did it again?", "Involve end users in testing earlier; plan a small pilot to measure time from complaint to identified run before and after; and extend reverse trace beyond the handle lot to filament and brass-wire lots."],
  ["How scalable is it?", "Fine for a prototype and a pilot on a few lines. Excel slows as registers grow and it isn't built for concurrent multi-user editing, user roles or an audit trail. For plant-wide use, the registers should move to a database, with Excel or Power BI on top."],
  ["Why a Production Run ID?", "Because every lookup needs a unique key. MATCH returns the first match, so a repeating key silently returns the wrong record. The Run ID is unique per manufacturing occurrence and every downstream record carries it."],
  ["Why can't the Batch Number be the key?", "It repeats. JHS-26433 appears on six runs in the demonstration data. Batch numbers are printed codes from a finite annual series, tied to packaging and regulatory records, so I didn't change them. I added a separate internal key instead."],
  ["How does reverse traceability work?", "Enter a component lot, e.g. handle lot HL-DBR-26-0519. COUNTIF over Master Traceability gives the number of runs (3), SUMIFS gives good units exposed (8,698), and INDEX with SMALL(IF()) lists each run with batch, date, machine, QC status and dispatch number. So recall scope is calculated, not estimated."],
  ["How is OEE calculated?", "Per run in OEE_Calculation: Availability = run time ÷ planned time; Performance = total output ÷ (run time × ideal speed ÷ 60); Quality = good ÷ total; OEE = A × P × Q. For any filter, the dashboard sums the minutes and units first and then divides."],
  ["Why ratio of sums?", "Averaging percentages gives a short run the same weight as a long one. Example: run A is 1 hour at 50% availability and run B is 9 hours at 90%. The average of ratios is 70%, but the true figure is (0.5 + 8.1) ÷ 10 = 86%. Summing numerators and denominators first gives the correctly weighted result."],
  ["What are the limitations?", "It's a prototype, not an enterprise MES: bounded scalability, no concurrent multi-user working, no user roles, no audit trail, accuracy depends on disciplined manual entry, no machine data capture (OEE is calculated after the event), and reverse trace is keyed on handle lot only. It also runs on a demonstration dataset, not live company data."],
  ["What is the future scope?", "Barcode scanning for batch and lot capture at source; RFID for movement tracking; SQL migration for scale, concurrency, roles and audit; IoT for run time, stoppages and counts from equipment; ERP integration for orders and inventory valuation; Power BI for wider distribution; predictive analytics only once a longer, verified history exists."],
  ["Is the complaint real?", "No. 'The bristles are getting off' is a traceability scenario I used to design and test the system. CMP-26-0024 is a record in the demonstration dataset."],
  ["Is the data real?", "The only figure from actual plant observation is the line study: 675 effective minutes, 67,500 ideal, about 40,000 actual, 40.7% variance. Everything in the workbook is a demonstration dataset with Amway, Chicco and Dabur modelled as client brand accounts with fictional operational data. It isn't the company's production records."],
  ["Does the system read the customer's photograph?", "No. There is no image recognition or automatic batch extraction. Reading the four fields from the pack is a human step."],
  ["What is Master Traceability?", "The calculation-layer sheet with one consolidated row per production run (78 columns): production, handle/material genealogy, QC, dispatch, OEE, and validation and completeness status. Every report looks up this one row, so the Trace Report, Reverse Trace and Complaint Tool can never contradict each other."],
  ["Why no macros or VBA?", "Macros are often blocked by IT policy, are harder for others to maintain, and hide logic. Formulas, named ranges, data validation and native charts are transparent and auditable by anyone who opens the file."],
  ["How did you test it?", "Scenario testing (the complaint path end to end, repeated batch numbers, a lot reaching several runs), 106 calculation checks against independently computed values, and 80 filter-context checks that each KPI responds correctly to the filters."],
  ["What's the difference between ERP and MES?", "ERP plans and accounts: orders, purchasing, inventory value, finance. MES executes and records on the floor: what ran, on which machine, with which lots, what QC found, what stopped. My workbook is the MES layer; ERP integration is future scope."],
];

module.exports.numbers = [
  ["Internship", "1 June – 17 July 2026 (seven weeks), Operations, Kala-Amb (HP)"],
  ["Workbook", "JHS MES v3.0: 27 sheets, 5 layers, no macros"],
  ["Testing", "106 calculation checks + 80 filter-context checks"],
  ["Line study (real)", "720 − 30 − 15 = 675 min × 100 units/min = 67,500 ideal; ~40,000 actual; ~27,500 gap; 40.7%"],
  ["Demo dataset", "1,529 runs over 90 days (08-Jun-26 to 05-Sep-26); 364 batch numbers, each recurring 3–6 times"],
  ["Dashboard", "Actual 5,842,931 vs planned 6,630,870; efficiency 88.1%; OEE 74.0%; yield 97.6%; rejection 2.0%"],
  ["OEE breakdown", "Availability 84.6% × Performance 89.6% × Quality 97.6% = 74.0%"],
  ["Story case", "CMP-26-0024 → JHS-26433 (6 matches) → 4 fields → PR-2026-00630"],
  ["PR-2026-00630", "480 planned, 263 down (2 material shortages), 217 run; A 45.2%, P 85.2%, Q 98.3%, OEE 37.9%"],
  ["Reverse trace", "HL-DBR-26-0519 → 3 runs → 8,698 good units exposed"],
];

module.exports.traps = [
  "Don't call the bristle complaint a real complaint from the internship. It's a design scenario and a demonstration-dataset record.",
  "Don't claim time saved, percentage improvement or ROI. Nothing was formally measured.",
  "Don't present dashboard figures as JHS performance. They come from a demonstration dataset.",
  "Don't generalise the 40.7% line-study gap to the company. It's one line, one cycle.",
  "Don't say SQL, barcode, RFID, IoT or Power BI are implemented. They're all future scope.",
  "Don't say the system finds the root cause. It gives QA the right record quickly; root cause is still QA's analysis.",
  "Don't say the system reads the photograph. Reading the pack is a human step.",
];

module.exports.slideTitles = [
  "Imagine a customer sends us this", "The complaint", "How do we find out what happened?", "What does the pack tell us?",
  "Why isn't the Batch Number enough?", "What identifies one manufacturing occurrence?", "Where was I?", "Who is JHS?",
  "What does it look like on the ground?", "How did I spend seven weeks there?", "What did the induction teach me before the project began?",
  "What did the plant teach me about the system?", "How does material move through the plant?", "The plant had the data", "Where was the information, and why was it slow to use?",
  "What did twelve hours on one line show me?", "So where did 27,500 units go?", "What would the system need to answer?", "How did the project evolve?",
  "How did I structure it?", "What connects the records?", "Before I show you the system… (video)", "Can management see the overall picture?",
  "Can we drill from a KPI to the records behind it?", "Which manufacturing occurrence are we investigating?", "One record. One key.", "Once we find the right record, what can we see?",
  "For loose bristles, where would QA look first?", "Can we investigate the complaint end to end?", "If a material lot is implicated, where else did it go?", "But what tells us how efficiently it was produced?",
  "How efficiently did the lines perform?", "What changed?", "What did the project teach me?", "What this system is, and what it isn't",
  "The hardest part wasn't building the workbook", "It was understanding the operation…", "Thank you",
];
